service: messenger-scrapper

provider:
  name: aws
  runtime: nodejs8.10

package:
  exclude:
    - README.md
    - package-lock.json
    - package.json

functions:
  fetch:
    handler: handler.fetch

    events:
      - http:
          path: fetch
          method: get

plugins:
    - serverless-offline

custom:
  serverless-offline:
    port: 4000
